import js from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier";
import turboPlugin from "eslint-plugin-turbo";
import tseslint from "typescript-eslint";

/**
 * A shared ESLint configuration for the repository.
 *
 * @type {import("eslint").Linter.Config[]}
 * */
export const config = [
  js.configs.recommended, //Default configs
  eslintConfigPrettier, //Lets prettier handle code styles
  ...tseslint.configs.recommended, //Make ESLint udnerstand typescript
  {
    plugins: {
      turbo: turboPlugin,
    },
    rules: {
      "turbo/no-undeclared-env-vars": "warn", //Mostly not needed
    },
  },
  {
    ignores: ["dist/**"], //Ignores dist folder as they are autogenerated
  },
];
